language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - mysql
  - memcached
  - elasticsearch
  - redis-server

before_script:
  - tests/travis/install-php-runkit.sh
  - sh -c "if [ `php-config --vernum` -ge 50500 ]; then printf "yes\n" | pecl install apcu-beta; fi"
  - phpenv config-add tests/travis/php.ini
  - phpenv config-add tests/travis/php-$TRAVIS_PHP_VERSION.ini

  - composer self-update
  - composer install --dev
  - bin/cm app generate-config-local tests/travis/config.json
  - bin/cm app set-deploy-version

script: bin/phpunit tests/library/CM/Action/AbstractTest.php

notifications:
  email: false
