language: php

php:
  - 5.6
  - 7.0
  - 7.1

services:
  - mysql
  - memcached
  - elasticsearch
  - redis-server

addons:
  apt:
    sources:
      - mongodb-upstart
      - sourceline: 'ppa:gearman-developers/ppa'
    packages:
      - libgearman-dev
      - mongodb-org-server
      - re2c

before_script:
  - phpenv config-rm xdebug.ini
  - tests/travis/install-php-timecop.sh
  - tests/travis/install-pecl-gearman.sh
  - source tests/travis/install-phantomjs.sh
  - yes '' | travis_retry pecl install imagick
  - travis_retry pecl install stats-1.0.3
  - yes '' | travis_retry pecl install apcu-4.0.10
  - phpenv config-add tests/travis/php.ini
  - npm install -g autoprefixer@4.0.0
  - npm install -g uglify-js@2.4.13
  - npm install -g browserify@11.2.0
  - composer install
  - cp tests/travis/config.php resources/config/local.php
  - bin/cm app set-config deploy '{"deployVersion":'$(date +"%s")'}'

script:
  - bin/phpunit
  - bin/qunit

sudo: false

notifications:
  email: false
