language: php
sudo: false

php:
  - 5.4
  - 5.5

services:
  - mysql
  - memcached
  - elasticsearch
  - redis-server
  - mongodb

addons:
  apt:
    packages:
    - libgearman-dev
    - libsvm-dev
    - re2c

before_script:
  - tests/travis/install-php-runkit.sh
  - tests/travis/install-php-svm.sh
  - yes '' | travis_retry pecl install imagick
  - travis_retry pecl install stats
  - travis_retry pecl install gearman-1.0.3
  - if [ `php-config --vernum` -ge 50500 ]; then yes '' | travis_retry pecl install apcu-beta; fi
  - phpenv config-add tests/travis/php.ini
  - phpenv config-add tests/travis/php-$TRAVIS_PHP_VERSION.ini
  - npm install -g autoprefixer@4.0.0
  - npm install -g uglify-js@2.4.13

  - composer install
  - cp tests/travis/config.php resources/config/local.php
  - bin/cm app set-deploy-version

script: bin/phpunit

notifications:
  email: false
