version: '2'

services:
  test:
    build: .
    image: cargomedia/cm-application-test:latest
    container_name: cm-app
    command: './ci/test.sh'
    working_dir: /app/cm
    volumes:
      - data-cm:/app/cm/data
    depends_on:
      - mysql
      - mongo
      - memcached
      - elasticsearch
      - redis
      - gearman

  mysql:
    image: cargomedia/mysql:5.5.54
    volumes:
      - data-mysql:/var/lib/mysql

  mongo:
    image: cargomedia/mongo:2.6.12
    volumes:
      - data-mongo:/data/db

  memcached:
    image: cargomedia/memcached:1.4

  elasticsearch:
    image: cargomedia/elasticsearch:1.3.9
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data

  redis:
    image: cargomedia/redis:3.2.6
    volumes:
      - data-redis:/data/redis

  gearman:
    image: cargomedia/gearman:latest
    volumes:
      - data-gearman:/gearman/data

volumes:
  data-cm:
  data-mysql:
  data-redis:
  data-mongo:
  data-gearman:
  data-elasticsearch:
