version: '2'
services:

  cm:
    image: cargomedia/cm-application:latest
    command: /docker-run-php5-fpm
    volumes:
      - .:/app/cm
      - ./resources/config/_test.docker.php:/app/cm/resources/config/test.docker.php
      - ./resources/config/_local.docker.php:/app/cm/resources/config/local.docker.php
      - data-cm:/app/cm/data
    depends_on:
      - mysql
      - mongo
      - memcached
      - elasticsearch
      - redis
      - gearman
    environment:
      PHP_IDE_CONFIG: serverName=docker.cm.dev
    working_dir: '/app/cm'
    mem_limit: 2000000000
    memswap_limit: 3000000000
    mem_reservation: 512m

  mysql:
    image: cargomedia/mysql:5.5.54
    volumes:
      - data-mysql:/var/lib/mysql

  mongo:
    image: cargomedia/mongo:2.6.12
    volumes:
      - data-mongo:/data/db

  memcached:
    image: cargomedia/memcached:1.4

  elasticsearch:
    image: cargomedia/elasticsearch:1.3.9
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data

  redis:
    image: cargomedia/redis:3.2.6
    volumes:
      - data-redis:/data/redis

  gearman:
    image: cargomedia/gearman:latest
    volumes:
      - data-gearman:/gearman/data

volumes:
  data-cm:
  data-mysql:
  data-redis:
  data-mongo:
  data-gearman:
  data-elasticsearch:
