version: '2'
services:

  cm:
    image: cargomedia/cm-application:latest
    volumes:
      - data-cm:/app/cm/data
    depends_on:
      - mysql
      - mongo
      - memcached
      - elasticsearch
      - redis
      - gearman

  mysql:
    image: ${{build-mysql}}
    volumes:
      - data-mysql:/var/lib/mysql

  mongo:
    image: ${{build-mongo}}
    volumes:
      - data-mongo:/data/db

  elasticsearch:
    image: ${{build-elasticsearch}}
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data

  redis:
    image: ${{build-redis}}
    volumes:
      - data-redis:/data

  memcached:
    image: memcached:1.4
    command: "-p 11211 -m 2048 -u memcache -l 0.0.0.0 -c 10000 -v"

  gearman:
    image: pataquets/gearmand:latest
    command: "--job-retries=25 -q libsqlite3 --libsqlite3-db=/gearman/data/db.sqlite3"
    volumes:
      - data-gearman:/gearman/data

volumes:
  data-cm:
  data-mysql:
  data-redis:
  data-mongo:
  data-gearman:
  data-elasticsearch:
